### PR TITLE
Simple tests updates

### PR DESCRIPTION
**Pull request by uliska**
The changes have become more significant than intended, so I hope you're OK with them @Cecca .

The second to last commit causes the automtated build to fail - deliberately. So you should revert or remove that one completely (as it is only for demonstration purposes anyway)

### CODE REVIEW

**Comment by uliska** [comment]
See https://travis-ci.org/openlilylib/openlilylib/jobs/51856453
I think it has become quite nice :-)

**Comment by Cecca** [comment]
I'm fine with the changes you introduced, it looks really nice now :-)

I reverted the commit failing on purpose (btw, good idea to have support for explicitly including files), so if you are done we can merge this.

**Comment by uliska** [comment]
I'll merge this and try to implement the changes suggested by Travis support ( have already started) on top:
- separate out installation
- cache Lilypond

**Comment by Cecca** [comment]
Wonderful!

**Pull request merged**
