### PR TITLE
Fonts by Abraham

### PR DESCRIPTION
**Pull request by tisimst**
I've added a bunch of new music fonts that are 100% compatible with LilyPond. I've also included stylesheets to make them easier to use via the standard `\include` statement. I've also added licenses for each font, along with a README wherever I felt it would be useful.

I removed `*.pdf` so that I could include some immediately downloadable files for others' reference.

If you could please review and merge the commits, that would be awesome!

-Abraham

### CODE REVIEW

**Comment by uliska** [comment]
Hi Abraham, thanks for uploading this. I'm right now inspecting the files.
However, I strongly suggest _not_ to merge this pull request as it is but rather use it as a "code review tool". The reason for this is that I'm convinced that the significant amount of large binary files simply isn't appropriately placed in the `openlilylib` repository. We can keep the `font.scm` and the documentation here, at least until the patch is finally in LilyPond. But we definitely should store the actual font files somewhere else. 
I will have to look into doing this without leaving copies of the large files in the repository (through its history).

**Comment by tisimst** [comment]
That's fair. I'm actually ok with that. I've set up a Google site in which I've placed all these binary font files. Should we just put in a reference somewhere here so that people know where to get the fonts? Would it still be appropriate to have any example files and their PDFs here, or should they also be on my other site? I'm totally fine doing that.

I guess, from the regular user's standpoint, getting files from here might be a little daunting since it all seems a little too "nerdy" :) They could probably use a more "normal" looking web page for that.

**Comment by uliska** [comment]
I've just prepared a preliminary download page at http://fonts.openlilylib.org.
I've prepared a `.zip` file for each font.

**Comment by tisimst** [comment]
Hey, that looks great! I think that's just what people will need. I'm just thinking ahead, but when I want to update something, will I need you to upload them for me, or is there some way that I can have access to that site's source directory?

**Comment by uliska** [comment]
I didn't really think through that yet. It's an intermediate thing anyway. I assume I can give you an ftp account that only accesses that folder. But I'll consider it when I review your stuff in detail (maybe tonight)

On 25. Juli 2014 19:10:39 MESZ, tisimst notifications@github.com wrote:

> Hey, that looks great! I think that's just what people will need. I'm
> just thinking ahead, but when I want to update something, will I need
> you to upload them for me, or is there some way that I can have access
> to that site's source directory?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/openlilylib/openlilylib/pull/45#issuecomment-50177632

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by tisimst** [comment]
That would be nice. Let me know what you think of. 

**I've just added another music font (Ross)** that I've been working on. It comes from the glyph set found on page A-57 of Ted Ross's book _The Art of Music Engraving and Processing_. It's named after the author, if you didn't get that already.

**Comment by uliska** [comment]
Starting review. For reasons of time I'll probably only mention things that seem problematic (i.e. I'm leaving out everything that looks fine ...)

### Font Sampler

This is very nice.
However, I'm missing a license statement. You simply claim copyright on the file.
Generally we prefer licensing all material with CC BY-AS, which should also be suitable for that kind of file. Are you OK with that?

And, more important: it's missing a `font-register.ily`

### Nalada

It's good to have such a 'real' example.
But it would be cool if that could contain the different fonts in easily uncommentable ways.

### README

There are a few things that should be made more concrete, but I think we should discuss that at a later stage.

(Well, I think, nobody will understand what steps are necessary to "path" that `font.scm` file ;-) )

### Style-sheets

This is a nice thing. We should think about the include/directory structure when we know where everything will end up.

### The font folders

a) I'm missing a license statement for the font samplers.
b) There really should be some information on the individual fonts. Something like the FONTLOG that is only there for Bravura. I would like to know where these fonts come from or if they are original designs etc. And I think the OFL requires this too.

That's what I'm finding for now (it's _really_ late now here ...)

Best
Urs

**Comment by tisimst** [comment]
Thanks for the feedback. You go get some sleep :)

Yes, CC BY-SA should be fine for the samplers. Does this need to be at the bottom of each one?

The font sampler file I used that showcases all the fonts does have a `\include "font-register.ily"` statement at the top. Maybe you must missed it, or maybe you're not referring to that one. The other solo font samplers have that statement in their respective stylesheet, though it's not directly used since I'm making the respective font the global one, so maybe it's not necessary.

By _"easily uncommentable ways"_ do you mean putting in an `\include` line for each font stylesheet and commenting out all but one as a starting point? Like this:

```
\version "2.18.2"
\include "profondo.ily"
%\include "cadence.ily"
%\include "haydn.ily"
(etc.)
```

I'll work on a FONTLOG for each font that doesn't have one.

**Comment by uliska** [comment]
I think the CC BY-SA reference should be everywhere where you print (c) Abraham Lee currently, i.e. in the `copyright` header field. Plus a comment at the top of the respective files.

> The font sampler file I used that showcases all the fonts does have a \include "font-register.ily" statement at the top. Maybe you must missed it, or maybe you're not referring to that one. 

I _am_ referring to that `\include` statement and to the fact that this `.ily` file isn't found.

> By "easily uncommentable ways" do you mean putting in an \include line for each font stylesheet and commenting out all but one as a starting point? 

Yes, exactly. That way the user can immediately start using the fonts without first having to find out how to include them.

Regarding the FONTLOG I think a good idea would be to also provide a README.md for each font, telling something about the font, but not from the legal perspective. When inspecting such fonts it would be nice to know something about a) the origin (i.e. the original creator), b) intended use and optionally c) historical/stylistical classification

**Comment by tisimst** [comment]
Do mean that LilyPond can't find the `font-register.ily` file itself? Are you putting the entire stylesheets directory on the path? It's in that folder.

Thanks for the README recommendations. I'll work on those and the FONTLOGs as well.

**Comment by uliska** [comment]
Strange, I managed not to see that file in the stylesheets folder ...

**Comment by tisimst** [comment]
In favor of moving the bulk of these files to fonts.openlilylib.org, I'm going to close this pull request.

**Pull request closed without merging**
