### PR TITLE
Update snippet-template.ly

### PR DESCRIPTION
**Pull request by uliska**
Make the metainfo section more elaborate.
It looks quite long but I think it's better to have it 'feature-rich'

### CODE REVIEW

**Comment by jan-warchol** [comment]
Hi,
I've made some changes, mostly to make the template briefer.  I hope that i haven't forgotten about something we discussed.
(btw, there's a merge conflict - i will take care of that)

**Comment by jan-warchol** [comment]
Hmm.  The result is almost as if i had reverted all your changes :/

**Comment by uliska** [comment]
The merge conflict is probably due to that you edited README.md once on the snippet-template branch

**Comment by jan-warchol** [comment]
2013/9/3 Urs Liska notifications@github.com

> The merge conflict is probably due to that you edited README.md once on
> the snippet-template branch
> 
> yes.

**Comment by uliska** [comment]
I will fix that merge conflict and merge this branch now.

**Pull request merged**
