### PR TITLE
Testing and continuous integration

### PR DESCRIPTION
**Pull request by Cecca**
Since OpenLilyLib is a collection of interdependent libraries it is important to ensure that changes to one library don't break another one.

This pull request implements a first stub of testing infrastructure that takes a very simple approach. In the OpenLilyLib directory tree we can have files called `.simple-tests` whose content list LilyPond files we want to compile, possibly using different LilyPond versions. We then have a script, `test/simple_tests.py` that looks for these files and compiles them. If the exit code is non-zero, then the test is considered as failed.

Moreover, this pull request already configures [Travis CI](https://travis-ci.org), a free continuous integration service tightly integrated with Github, to test OpenLilyLib with LilyPond `2.18.2-1` and `2.19.15-1`.

This is by no means neither perfect nor complete, as a more robust solution will require some Scheme testing library to be included in test files, for instance to handle expected failures. However it can already catch [errors like this](http://lists.gnu.org/archive/html/lilypond-user/2015-02/msg00257.html) by trying different versions.

As @uliska  [pointed out](http://lists.gnu.org/archive/html/lilypond-user/2015-02/msg00286.html), another possiblity would be to go for a self-hosted Jenkins server on openlilylib.org . This is another viable option and would allow for far more customization, but I think that for the time being this simple solution will already be useful.

### CODE REVIEW

**Comment by uliska** [comment]
## Thank you for adding this. Unfortunately I may not have time to look into it tomorrow, and then I'll have no Lily computer until next tuesday. So I'd be happy if someone else could look after this PR.

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by uliska** [comment]
This is a first conceptual comment _before_ reading any code.

First of all: I think automated testing is an absolute requirement when we want to develop `openLilyLib` in the new structure in a healthy manner. For this a Continuous Integration server is probably the way to go. If we can make a Github based solution do what we need I'd prefer that over a self-hosted solution, simply because I'd prefer not to take too much responsibility on reliable and failure-proof work of the server. (For the same reason I don't suggest moving the repository itself from Github to my own server's Gitlab installation).  
For this I suggest installing a `staging` area/branch approach where any working branches have to be merged to `staging` rather than `master` and the CI server will only promote `master` when the tests have been run successfully. Maybe we could even hook such tests to the opening of pull requests somehow.

However, I _think_ I'd prefer an even more automatic solution which doesn't require us to maintain extra testing files. I think we should make it a requirement that all exposed functionality is covered by _usage examples_ - which is sane with regard to documentation anyway - and make the testing script process all usage examples then.

If usage examples should also cover expected failure conditions we should implement a (set of) command(s) for that so the actual compilation can still exit with non-zero status.

_@Cecca please tell me what you think about it before I start reading into your simple-test code_

In the end everything should be run from one script call (by the CI server):
- run tests
- merge into `master` (if successful, otherwise notify the appropriate persons about the failure)
- update and upload documentation

**Comment by uliska** [comment]
OK, more comments _after_ skimming through the files and a Travis CI primer.

Do I see correctly that you can (and do) tell Travis to download LilyPond (each time) and run it on its server? If that's true I think it would be worth considering to run the script not on the Travis server but on the openlilylib.org server. This would make it easier to have more than two LilyPond versions available (e.g. 2.16.2, 2.18.2, the latest development version _and_ "current master")  
I'm not sure if that would mean moving the whole CI integration to my server or if it is still practical to integrate Travis as the CI server with the Github repository and call an external script instead of a local one.

After all I'm not sure if a Continuous Integration server really is what we need. Maybe it would be more appropriate to "simply" set up our testing/documentation script as a web service on my server and call that upon pushes to Github. I mean, IISC everything we need to be covered has to be implemented in the script anyway, so it may make sense not to go through a separate CI server instance at all.

As for the tests themselves (as said I only _skimmed_ the code): There is a provision to mark minimal and maximal LilyPond versions a file is compatible with. The tests should respect this and exclude incompatible files (maybe logging that fact) to avoid false failures.

**Comment by Cecca** [comment]
> Do I see correctly that you can (and do) tell Travis to download LilyPond (each time) and run it on its server?

Yes, it is true. In fact you can configure as many LilyPond versions as you like. Currently I configured only two of them, but if in the file `.travis.yml` you write

``` yaml
env:
  - LILY_PLATFORM=linux-64 LILY_VERSION=2.16.2-1
  - LILY_PLATFORM=linux-64 LILY_VERSION=2.18.2-1
  - LILY_PLATFORM=linux-64 LILY_VERSION=2.19.15-1
```

then the server will test the code against three versions of lilypond.

> After all I'm not sure if a Continuous Integration server really is what we need.

I think that using a CI server is the simplest thing we can do to have automated tests. Setting up a testing/documentation script as a web service would require to write and test it, maintain the infrastructure, and integrate it with Github. In the end the result would be something that is very similar to a CI server, but less tested and with the additional maintainance burden.

I agree that as of now Travis CI does not support LilyPond out of the box, hence we have to develop a custom build script. However, what Travis-CI does on our behalf is to maintain the infrastructure, the connection with Github and so on.

Moreover, there is an important feature of CI servers that would be missing in a custom implementation. Each build is performed in _isolation_, that is in a vanilla environment. Every time a build is triggered, a new virtual machine is brought up to run the testing code. This is really important to catch a category of subtle bugs, those caused by differences between people's environments. Using a fresh virtual machine every time simulates the situation of a new user that is setting up everything for the first time. Thus success and failure do not depend on the particular configuration that can be found on the developer's computer or on the self-hosted server performing builds. 

> The tests should respect this and exclude incompatible files (maybe logging that fact) to avoid false failures.

With commit  ee50f9f I introduced the ability to skip files for which the version of Lilypond in use is not sufficient. This is done automatically by looking for the `\version` line in the test file. If the required version is greater than the one in use, then the test is skipped.

As for your final points in your previous comment
- The script already runs all the tests listed in `.simple-tests` files
- I don't know if a CI server can automatically merge `git` branches. I'm not sure if this is desirable.
- Automatic notification. If a build fails, then the CI server notifies the developer by email.
- Update and upload documentation: this can be done with a hook in the build process of the CI server

**Comment by Cecca** [comment]
An extra comment on the nature of testing files.

I completely agree with you that it's desirable to not have to maintain separate testing files. Right now the only thing we need to maintain besides the examples are these `.simple-tests` files. Those are required to let the script know which files should be used as tests and which ones should not.

**Comment by uliska** [comment]
Am 19.02.2015 um 15:13 schrieb Cecca:

> ```
> Do I see correctly that you can (and do) tell Travis to download
> LilyPond (each time) and run it on its server?
> ```
> 
> Yes, it is true. In fact you can configure as many LilyPond versions 
> as you like. Currently I configured only two of them, but if in the 
> file |.travis.yml| you write
> 
> env:
>    -LILY_PLATFORM=linux-64 LILY_VERSION=2.16.2-1
>    -LILY_PLATFORM=linux-64 LILY_VERSION=2.18.2-1
>    -LILY_PLATFORM=linux-64 LILY_VERSION=2.19.15-1
> 
> then the server will test the code against three versions of lilypond.

OK. This won't work with the "current master" idea, but that's not 
really important anyway.
Maybe it would be possible to request Travis to add support for LilyPond 
versions? Maybe with the argument that this would avoid downloading and 
"installing" two (or more) big packages for each run.

> ```
> After all I'm not sure if a Continuous Integration server really
> is what we need.
> ```
> 
> I think that using a CI server is the simplest thing we can do to have 
> automated tests. Setting up a testing/documentation script as a web 
> service would require to write and test it, maintain the 
> infrastructure, and integrate it with Github. In the end the result 
> would be something that is very similar to a CI server, but less 
> tested and with the additional maintainance burden.
> 
> I agree that as of now Travis CI does not support LilyPond out of the 
> box, hence we have to develop a custom build script. However, what 
> Travis-CI does on our behalf is to maintain the infrastructure, the 
> connection with Github and so on.
> 
> Moreover, there is an important feature of CI servers that would be 
> missing in a custom implementation. Each build is performed in 
> /isolation/, that is in a vanilla environment. Every time a build is 
> triggered, a new virtual machine is brought up to run the testing 
> code. This is really important to catch a category of subtle bugs, 
> those caused by differences between people's environments. Using a 
> fresh virtual machine every time simulates the situation of a new user 
> that is setting up everything for the first time. Thus success and 
> failure do not depend on the particular configuration that can be 
> found on the developer's computer or on the self-hosted server 
> performing builds.

This is a good and maybe deciding point.

> ```
> The tests should respect this and exclude incompatible files
> (maybe logging that fact) to avoid false failures.
> ```
> 
> With commit ee50f9f 
> https://github.com/openlilylib/openlilylib/commit/ee50f9fff81d73df2ebd2fb9757da2930af348f7 
> I introduced the ability to skip files for which the version of 
> Lilypond in use is not sufficient. This is done automatically by 
> looking for the |\version| line in the test file. If the required 
> version is greater than the one in use, then the test is skipped.

OK, fine. But we'll have to modify it to a) use the header fields (if 
present) and check for greater and lesser versions (because files can 
also be compatible _up to_ a certain version).

> As for your final points in your previous comment
> - The script already runs all the tests listed in |.simple-tests| files

Well, maybe we should discuss separately if we should rely on the 
.simple-tests or the usage-examples approach. I think both have pros and 
cons.

> - I don't know if a CI server can automatically merge |git|
>   branches. I'm not sure if this is desirable.

It is desirable that the CI process should promote  `master` to 
`staging` if the build succeeds.
Of course if the repository were hosted on openlilylib (and the script 
too) this would be no problem, but I don't know if the Github API can be 
used to merge branches (I only know about the possiblilty to download 
JSON files to get information about anything going on in a Github 
repository.

> - Automatic notification. If a build fails, then the CI server
>   notifies the developer by email.

It would be great if we could specify this some more so the notification 
would go directly to the maintainer of the "affected" library (if that 
can be determined). Otherwise we could set up a mailing list as the 
notification target that distributes the info to all library maintainers.

> - Update and upload documentation: this can be done with a hook in
>   the build process of the CI server

**Comment by Cecca** [comment]
> Maybe it would be possible to request Travis to add support for LilyPond versions? Maybe with the argument that this would avoid downloading and "installing" two (or more) big packages for each run.

I think that we can give it a try.

> OK, fine. But we'll have to modify it to a) use the header fields (if present) and check for greater and lesser versions (because files can also be compatible _up to_ a certain version).

I wasn't aware of that, how are these upper bounds specified? I couldn't find any example in the `openLilyLib` repository.

> Well, maybe we should discuss separately if we should rely on the .simple-tests or the usage-examples approach. I think both have pros and cons.

I think that the `usage-examples` is simpler to maintain, but the `.simple-tests` approach gives some more control, since some files in `usage-examples` may not be meant to be compiled standalone.

> It is desirable that the CI process should promote `master` to `staging` if the build succeeds. Of course if the repository were hosted on openlilylib (and the script too) this would be no problem, but I don't know if the Github API can be used to merge branches (I only know about the possiblilty to download JSON files to get information about anything going on in a Github repository.

I really have no idea about how to achieve this.

> It would be great if we could specify this some more so the notification would go directly to the maintainer of the "affected" library (if that can be determined). Otherwise we could set up a mailing list as the notification target that distributes the info to all library maintainers.

As per [the documentation](http://docs.travis-ci.com/user/notifications/), email notifications are sent to the committer and the commit author. Moreover, custom recipients may be specified in the configuration file. So a mailing list is also possible.

---

Besides this, I'd really like to integrate this functionality in openLilyLib as soon as possible, even if right now it's not feature complete. After all, using the `.simple-tests` file is completely optional, so there will be no imposed burden on developers, however I'll feel more comfortable in having this safety net (albeit incomplete).

**Comment by uliska** [comment]
Am 21.02.2015 um 10:52 schrieb Matteo Ceccarello:

> ```
> Maybe it would be possible to request Travis to add support for
> LilyPond versions? Maybe with the argument that this would avoid
> downloading and "installing" two (or more) big packages for each run.
> ```
> 
> I think that we can give it a try.

I've just sent them an email

**Comment by Cecca** [comment]
Thank you :-)

Anyway, as you can see in the output of [this build](https://travis-ci.org/Cecca/openlilylib/jobs/50496454#L97), downloading the LilyPond installer on their machines takes only 2 seconds, so that's not that much overhead.

**Comment by uliska** [comment]
OK, nevertheless it's a waste of bandwidth, and maybe the prefer adding 
a rarely used "compiler" over this.

Anyway, I assume you integrated it with a fork of the repository 
(guessing from the above link)? So would you mind activating it for the 
main repository? Or are you lacking privileges for this? In that case 
could you please give me a hint instead how to proceed?

**Comment by uliska** [comment]
http://docs.travis-ci.com/user/pull-requests/ looks very promising. Maybe we could use this and don't need the staging area/branch at all?

**Comment by Cecca** [comment]
> OK, nevertheless it's a waste of bandwidth, and maybe the prefer adding a rarely used "compiler" over this.

I agree, it's a waste, it would be much better to have official support

>  Anyway, I assume you integrated it with a fork of the repository (guessing from the above link)? So would you mind activating it for the main repository? Or are you lacking privileges for this? In that case could you please give me a hint instead how to proceed?

Yes, I activated it on a fork. Unluckily I cannot activate it for openLilyLib because I'm not an admin. However, it's really simple. You just need to go here: https://travis-ci.org/profile/openlilylib and click on "sign in with github". Then, you should see the openLilyLib repository. You can toggle it on and it's done.

This pull request already includes a working `.travis.yml` configuration file, so after you activate the repo we should be good to go.

> http://docs.travis-ci.com/user/pull-requests/ looks very promising. Maybe we could use this and don't need the staging area/branch at all?

Yes, maybe leveraging this feature is simpler.

**Comment by uliska** [comment]
> >  Anyway, I assume you integrated it with a fork of the repository
> > (guessing from the above link)? So would you mind activating it for the
> > main repository? Or are you lacking privileges for this? In that case
> > could you please give me a hint instead how to proceed?
> 
> Yes, I activated it on a fork. Unluckily I cannot activate it for
> openLilyLib because I'm not an admin. However, it's really simple. You
> just need to go here: https://travis-ci.org/profile/openlilylib and
> click on "sign in with github". Then, you should see the openLilyLib
> repository. You can toggle it on and it's done.

I did so and created a dummy pull request. Of course this failed as the test suite isn't merged yet, but it shows that the integration does work.

> > http://docs.travis-ci.com/user/pull-requests/ looks very promising.
> > Maybe we could use this and don't need the staging area/branch at all?
> 
> Yes, maybe leveraging this feature is simpler.

My first test also shows that the build fails - which means we _can_ use that and don't need the staging area :-)

**Comment by uliska** [comment]
I'm right now working on the test script and adding some minor improvements.

One suggestion regarding the test case selection interface.
@Cecca what would you think about combining the approaches by making the tests automatically compile _all_ usage examples files and let authors _exclude_ such files manually by adding them to `.simple-test-excludes` files? That would make the testing automatic (don't rely on authors adding their files to the test suites) but still provide the option to skip given files.

**Comment by Cecca** [comment]
Urs, thank you for the improvements. I like this combined approach! Right now I'm not at my development machine, I'll work on it tomorrow.

**Comment by Cecca** [comment]
@uliska, I implemented your combined strategy for test selection. Moreover, I cherry picked your commit correcting the version regex.

It looks like everything is working :-)

**Pull request merged**
