### PR TITLE
New files for shapeTieColumn function

### PR DESCRIPTION
**Pull request by ksnortum**
New files and directory for the shapeTieColumn function

### CODE REVIEW

**Comment by uliska** [comment]
Thanks for that addition.
As I'm not at home I can't process or even understand it for several days.

Best
Urs

On 14. Juni 2014 02:17:51 MESZ, Knute Snortum notifications@github.com wrote:

> You can merge this Pull Request by running:
> 
>  git pull https://github.com/ksnortum/snippets master
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/openlilylib/snippets/pull/34
> 
> -- Commit Summary --
> - New files for shapeTieColumn function
> 
> -- File Changes --
> 
> A notation-snippets/shaping-bezier-curves/shape-tie-column/README.md
> (17)
> A
> notation-snippets/shaping-bezier-curves/shape-tie-column/definition.ily
> (39)
> A notation-snippets/shaping-bezier-curves/shape-tie-column/example.ly
> (29)
> 
> -- Patch Links --
> 
> https://github.com/openlilylib/snippets/pull/34.patch
> https://github.com/openlilylib/snippets/pull/34.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/openlilylib/snippets/pull/34

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ksnortum** [comment]
I have another snippet to submit.  Should I wait until this one is merged
(or else my pull request will have this one and the new one), or should I
put the new one in a branch?

Knute Snortum
(via Gmail)

**Comment by uliska** [comment]
Hi Knute,

your email on lilypond-user earlier this day reminded me of your open 
pull request. Sorry. I will process that ASAP.
But you should always put independent submissions in independent 
branches (based on master each), so they won't step on each others' toes.

Best
Urs

PS: I intend to include Jan-Peter's solution too, but I don't think 
that's a problem, just two alternative options for the user.

Am 20.06.2014 15:27, schrieb Knute Snortum:

> I have another snippet to submit.  Should I wait until this one is merged
> (or else my pull request will have this one and the new one), or should I
> put the new one in a branch?
> 
> Knute Snortum
> (via Gmail)
>

**Comment by ksnortum** [comment]
I cleaned up and resent the pull requests.  I would think that "separate
branches" is now burned into my memory!

Knute Snortum
(via Gmail)

**Comment by jan-warchol** [comment]
Hello,

i'm sorry for the delay.  The function is now merged - thanks!

Janek

2014-06-14 2:17 GMT+02:00 Knute Snortum notifications@github.com:

**Pull request closed without merging**
