### PR TITLE
original-breaks/definitions.ily: Add "" in header to prevent errors

### PR DESCRIPTION
**Pull request by skiasaurus**
Without these quotes, files that include this one compile with errors that complain "not a markup."

### CODE REVIEW

**Comment by skiasaurus** [comment]
I'm still new to Git and this is my first pull request, so if I'm doing it wrong please let me know...

**Comment by uliska** [comment]
Daniel Rosen notifications@github.com schrieb:

> I'm still new to Git and this is my first pull request, so if I'm doing
> it wrong please let me know...

It's perfect, I just can't merge it from the phone ;-)

## Thanks for the fix!

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jan-warchol** [comment]
Hi,

this looks quite strange to me: the pull request contains 3 commits affecting quite different snippets, and it was closed - ?

I assume that you wanted to propose just this commit https://github.com/skiasaurus/snippets/commit/9e92b4d08b7f0e4ef8ef2270dfc88e877975c2a6 ?

As for LilyJazz stuff, it's great to see you working on it!  Please contact Federico Bruni, [who's working on this as well](http://lists.gnu.org/archive/html/lilypond-user/2013-11/msg00917.html) to coordinate your efforts.

**Comment by skiasaurus** [comment]
> Hi,
> this looks quite strange to me: the pull request contains 3 commits affecting quite different snippets, and it was closed - ?
> I assume that you wanted to propose just this commit skiasaurus@9e92b4d ?

Correct. I'm new to Git and I'm still figuring out how pull requests work.

> As for LilyJazz stuff, it's great to see you working on it! Please contact Federico Bruni, who's working on this as well to coordinate your efforts.

All I did was add the files that were sent around on the lilypond-user list a few weeks ago as they were. I haven't touched them.

**Comment by jan-warchol** [comment]
2013/12/1 Daniel Rosen notifications@github.com

> Correct. I'm new to Git and I'm still figuring out how pull requests work.

Ok.  Don't worry, i just grabbed the commits (the one about original breaks
and vocal partcombine) and applied them manually - they are in master now.
Thanks!

> > As for LilyJazz stuff, it's great to see you working on it! Please
> > contact Federico Bruni, who's working on this as well to coordinate your
> > efforts.
> 
> All I did was add the files that were sent around on the lilypond-user
> list a few weeks ago as they were. I haven't touched them.

Ok, so i'll wait for Frederico.  Feel free to contact him and help out :-)

best,
Janek

**Comment by uliska** [comment]
Hi, so I seem to be late :-)

I'm going to reply to your "Git question email" right now.

**Pull request closed without merging**
