### PR TITLE
smufl example scores

### PR DESCRIPTION
**Pull request by nhthn**
This contains a minor Script alignment fix and adds two complete public-domain score examples.

(I'm still a newbie to Git and version control, so my apologies if I screwed something up.)

### CODE REVIEW

**Comment by jan-warchol** [comment]
I'm not sure about including pdfs, as they are quite heavy (compared to the other stuff in the repo).

Btw, have you seen [this?](http://lilypondblog.org/2014/01/engraving-contest-relaunched/)
I saw that you committed a work-in-progress engraving of one of the challenges, would you like to continue?

**Comment by jan-warchol** [comment]
@uliska what's your opinion on pdfs?

**Comment by nhthn** [comment]
I've retroactively branched off the example scores into the smufl-examples branch from my repo, so now this pull request is just a script alignment fix. Sorry for the confusion.

**Comment by jan-warchol** [comment]
Thanks!

**Pull request merged**
