### PR TITLE
GridLY 0.4.0

### PR DESCRIPTION
**Pull request by Cecca**
Theis is release 0.4.0 of GridLY, see the [changelog](https://github.com/openlilylib/openlilylib/blob/bb91a69aec3ae6f6f2e9dc331cbefafcdea6d21a/ly/gridly/CHANGELOG.md) for details.

### CODE REVIEW

**Comment by uliska** [comment]
I will have a look at the comments in the example.ly file. I think there are some issues left in there, but I'm not completely sure. Will do that later today (hopefully)

**Comment by Cecca** [comment]
Now on the command line `master` and `gridly/devel` merge cleanly, I don't know why here on github the PR says that it can't merge them automatically.

Anyway, when you are OK with these changes just let me know and I'll merge manually this branch with `master`

**Comment by uliska** [comment]
As said I'll have to have a second look, presumsbly today.

**Comment by uliska** [comment]
As written in #84 I'm nearly fine with this. So if you don't have any issues with my PR on top of this one please merge both in turn.

**Comment by uliska** [comment]
@Cecca I checked your formatting addition and I'm fine with it. Do you wait for me to comment or is there anything else?

From my perspective you can now merge this (goes without hassles on the command line)

**Comment by Cecca** [comment]
OK, I just merged it.

**Comment by uliska** [comment]
Great. So now I can start adding another "real world" use for GridLY :-)

Thank you for sharing your project BTW. It is encouraging to see GridLY in action so smoothly. I'm sure we can integrate it in "Das trunkne Lied", even if the complete instrumental parts have been entered with the "classical" grid approach.

**Pull request merged**
