### PR TITLE
Code reformatting

### PR DESCRIPTION
**Pull request by sincere-music**
In order to make the code in this folder easier to grasp for others (such as me :-)) I reformatted the code by adding line breaks and re-indenting. I hope this isn’t too controversial.

### CODE REVIEW

**Comment by uliska** [comment]
Don't know why you closed it again. But I wanted to say that there is an open pull request that might as well conflict with yours.

**Comment by sincere-music** [comment]
Sorry, I did a mess here. Actually, there are two other commits which would belong into this, but I opened separate branches for them.

**Comment by sincere-music** [comment]
Should I merge the :patch-1, :patch-2 and :patch-3 branches into sincere-music:openlilylib and create a new pull request?

**Comment by uliska** [comment]
That sounds good.
But please take https://github.com/openlilylib/openlilylib/pull/79 into account. Jan-Peter is waiting for a significant update to be merged (sorry, still no chance to do that so far), and this will surely produce merge conflicts.
Maybe you should branch your change off from his working branch? That would make your modifications go into master later, but they wouldn't get lost in any case.

**Comment by sincere-music** [comment]
I’ve now merged all three branches into sincere-music:openlilylib. How would I ‘branch my change off from his working branch’?

**Comment by uliska** [comment]
I assume you _do_ have a local repository (just asking because of the `patch-1` etc. stuff.

You have to do:
- pull everything locally
- checkout the branch where you have merged your three commits
- create a new branch from that (this is actually only a fallback solution, but may come in handy if you have merge conflicts)
- try: `git rebase jpv/edition-engraver`
- if that gives too many rebase conflicts do `git rebase abort` and come back

**Comment by sincere-music** [comment]
Ok. Until now I did this in the online GUI, but it’s certainly easier to use the command line, as I do with my typesetting repos (which are hosted on bitbucket).

**Comment by uliska** [comment]
I think doing this is actually impossible from the web interface

Am 29. Mai 2015 19:34:31 MESZ, schrieb Simon Albrecht notifications@github.com:

> Ok. Until now I did this in the online GUI, but it’s certainly easier
> to use the command line, as I do with my typesetting repos (which are
> hosted on bitbucket).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/openlilylib/openlilylib/pull/121#issuecomment-106881540

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by sincere-music** [comment]
The `git rebase jpv/edition-engraver` part didn’t work: it gives
`fatal: Needed a single revision
invalid upstream jpv/edition-engraver`
Thanks for your help…

**Pull request closed without merging**
