### PR TITLE
Preview mode considerations

### PR DESCRIPTION
**Pull request by uliska**
I've put the stuff discussed by email into a more explicit representation in our repo.

Best way to check the pull request out is to simply switch to the `preview-mode` branch and inspect the [draft-mode](https://github.com/openlilylib/snippets/tree/preview-mode/draft-mode) directory.

### CODE REVIEW

**Comment by jan-warchol** [comment]
Generally LGTM, but i suggest that you word-wrap commit messages and remove trailing spaces (you may use [this script](https://github.com/janek-warchol/cli-tools/blob/master/scripts/remove-trailing-whitespace.py)).

Also, i don't like the name "draft mode".  We both became familiar with it, but i'm afraid it's not very descriptive.  What about "debugging layout" or "debugging output"?

**Comment by uliska** [comment]
Well, I'm open for discussion, but _I_ find it descriptive. BTW LaTeX also has the general documentclass option [draft] which for example highlights 'overfull boxes' with black background.

In any case a label should be reasonably short. Maybe 'debug-mode'?

**Comment by uliska** [comment]
Suggestion: `debug-layout`

**Comment by jan-warchol** [comment]
I'd prefer `debugging-layout` as it seems more gramatically correct to me (since these snippets are meant for continuous application), but `debug-layout` is good enough.

Thanks for pinging me!  I've spent almost whole day thinking about the "github" issue and discussions with David, and the situation is better now.

**Comment by uliska** [comment]
All command line options are imperative, e.g. `debug-lexer`, `include-book-title-preview`, so I think `debugging-` isn't appropriate.

The question is rather if we want to place our mode between all the other `debug-` CL options or not?
I'm not completely sure, but I think it's OK.

**Comment by jan-warchol** [comment]
2013/9/23 Urs Liska notifications@github.com

> All command line options are imperative, e.g. debug-lexer,
> include-book-title-preview, so I think debugging isn't appropriate.
> 
> Good point.
> We could name the option `debug-layout` and yet put the stuff in a folder
> named `debugging-layout`, but i don't insist.  Do as you wish.

Janek

**Comment by uliska** [comment]
OK, I've done a few things and created a new branch and pull request.
I suggest using the folder in the `snippets` repos merely as a place for discussion (with md files), and to keep the relation to the snippets we will use (as they will mostly be also in the snippets repo - I think some duplication of code will be inevitable).

Further I suggest to create a github.com/openlilylib/frescobaldi fork, create a (long-running) `debug-layout` mode and work in that. Branch feature branches off from that individually and create pull requests against that. Somehow I find that more natural than to push and pull stuff around between our independent forks. And it seems more straightforward to encourage others like David N and Harm to directly contribute.
Or do you think that's an unnecessary level of complexity?

**Comment by uliska** [comment]
Just did it and think it's OK this way.

It's just important to note that pull requests _must_ be opened againts the `debug-layout` branch and not to the (automatically selected) `master` branch.

We should document that on the fork's Wiki page (in this case I think the Wiki is best because we can't insert Markdown files in the Frescobaldi sources ...

**Comment by uliska** [comment]
Done: https://github.com/openlilylib/frescobaldi/wiki

**Comment by jan-warchol** [comment]
ok
(as i'm catching up with things this just a confirmation that i've read this and don't have objections)

**Pull request closed without merging**
