### PR TITLE
Function for metric modulation as markup

### PR DESCRIPTION
**Pull request by PeterBjuhr**

### CODE REVIEW

**Comment by jan-warchol** [comment]
Very nice!  I apologize that you had to wait.  I have some suggestions, but i'll add them separately.

**Comment by PeterBjuhr** [comment]
Thanks, no problem! All suggestions are appreciated.

**Comment by uliska** [comment]
Hey, I just had the opportunity to check your snippet - it's great!

I have one suggestion (gave it a try but failed miserably ...): I would like to have the arrows optional because they aren't standard notation.

I don't know how to insert a condition in the `#{ #}` block, and when I tried to define a variable with either `"←"` or `""` and use this in the markup construct I get a `not a markup` error.

**Comment by PeterBjuhr** [comment]
Thanks!

The arrows are more or less standard when you have different note values, because there is a confusion between the older notation practice of having the new value on the left side and a newer practice of having them on the right. 

My initial idea was that the function should only cover cases where the arrows where needed and that the markup for simpler variants could easily be done without a function. But maybe it would be nice to make the function more general.

**Comment by PeterBjuhr** [comment]
Thanks for all suggestions. I think I start with changing from `\note-by-number` to `\note`.

**Pull request merged**
