### PR TITLE
GridLY: Some interface renamings

### PR DESCRIPTION
**Pull request by uliska**
Implements parts of the discussion in #64

### CODE REVIEW

**Comment by Cecca** [comment]
Thank you Urs. Can I work on this branch before merging it in `gridly/development`?

**Comment by uliska** [comment]
Ok. I won't touch it anymore.

**Comment by Cecca** [comment]
I wanted to still provide all the old functions with a deprecation warning, since I feel that public API changes should be as smooth as possible, otherwise our users would get upset.

Working on this, I got stuck on issue #72. I'm first going to fix that before continuing the work here

**Comment by Cecca** [comment]
As you may have read on my latest commit on issue #64, I renamed a couple of functions. I ended up doing that on the `gridly/development` branch instead of this one because I want the change to be smoother, thus I provided deprecation warnings. (this is mainly because I have many files depending on gridly already, and I can't change them all at the same time)

**Comment by Cecca** [comment]
@uliska shall we delete this branch, now that gridly made its way into master? So we can keep the repo clean

**Comment by uliska** [comment]
Yes. I think you also have a stale branch on your fork which could be deleted. Maybe you could consider removing the fork altogether.

**Comment by Cecca** [comment]
Yes, it is no longer needed

**Pull request closed without merging**
