### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by uliska**
Create new pull request (after #82) because the old one didn't seem to trigger Travis builds anymore.

Not to be merged yet.

### CODE REVIEW

**Comment by Cecca** [comment]
I don't know if you are already doing it, but you can sort of simulate the Travis CI environment on your computer by doing the following

```
export CI=true
export LILY_PLATFORM=linux-64
export LILY_VERSION=stable
python test/install_lilypond.py
./test/simple_tests.py
```

**Comment by uliska** [comment]
@Cecca I'm now ready with this, so you can review and merge it. If you want to fully test it I suggest doing the following things in turn:
- add a `.simple-tests-includes` file somewhere which points to a non-existent LilyPond file.  
  This will show you that the include mechanism works and how the script handles failed tests.  
  (You can do this locally without pushing)
- delete the Travis cache (to check installation)

**Comment by uliska** [comment]
Maybe we should rename all `simple-tests` references to something like `automated-tests`? I think "simple" has a misleading connotation.

This would imply:
- simple-tests.ly
- reference in `.travis-yml`
- variables `test_excludes_fname` and `test_includes_fname`
- existing exclude file(s)

What do you think?

**Comment by Cecca** [comment]
@uliska thank you for all your work on this! I'm OK with all you changes, so we can merge it right now.

The "simple" in the name is there because when it started out it was simpler and handled less cases ;-) Since now it's more feature complete, I think it's appropriate to rename it, and `automated-tests` looks like a fine choice. So 
- `simple-tests.py` -> `automated-tests.py`
- `.simple-tests-include` -> `.automated-tests-include`
- `.simple-tests-exclude` -> `.automated-tests-exclude`

If you prefer we can merge this pull request and I can handle the renaming with another PR

**Comment by uliska** [comment]
I'm doing it within this PR, and when the next automated test succeeds I'll merge it.

But I just noticed that my test include file wasn't respected, so there seems to be a bug remaining.

**Comment by Cecca** [comment]
I tested it locally and it was working. Maybe it's just the file being misnamed?

**Comment by uliska** [comment]
Oops: the bug report was a false alarm. Wasn't tested online because I didn't push it. Offline it did work, just not the one time I ran the renamed script and hadn't renamed the include file yet ;-)

Apart from this the checks after renaming succeed, so I merge it now.

**Comment by Cecca** [comment]
Thank you. I also updated my PR #77 to reflect these changes in names

**Pull request merged**
